[buildPlans.iosevka-serifish]
family = "Iosevka Serifish"
spacing = "fixed"
width = "condensed"

[buildPlans.iosevka-serifish.variants.design]
one = "base"
l = "serifed"
i = "serifed"
capital-i = "serifed"
zero = "slashed"
